base_app/urls.py
from django.urls import path

from base_app import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
]

gerenciador/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gerenciador_base_app.urls')),
    path('clientes/', include('clientes.urls')),
    path('ordem-servico/', include('ordens_de_servico.urls')),
    path('funcionario/', include('funcionarios.urls')),
    path('produtos/', include('produtos.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produtos/urls.py
from django.urls import path

from produtos import views

urlpatterns = [
    path('marca/cadastro', views.CadastrarMarca.as_view(), name='cadastrar_marca'),

    path('cadastro', views.CadastrarProduto.as_view(), name='cadastrar_produto'),
    path('listar', views.ListarProdutoView.as_view(), name='listar_produtos'),
    path('editar/<int:pk>/', views.EditarProduto.as_view(), name='editar_produto'),
    path('excluir/<int:pk>/', views.ExcluirProduto.as_view(), name='excluir_produto'),
]

produtos/models.py
from django.db import models


class Marca(models.Model):
    nome = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'

    def __str__(self):
        return self.nome


class Produto(models.Model):
    nome = models.CharField(max_length=100)
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    quantidade = models.IntegerField()
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'

    def __str__(self):
        return self.nome

produtos/forms.py
from django import forms

from produtos.models import Produto, Marca


class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = '__all__'


class MarcaForm(forms.ModelForm):
    class Meta:
        model = Marca
        fields = ['nome']

produtos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DeleteView

from produtos.forms import ProdutoForm, MarcaForm
from produtos.models import Produto


class CadastrarProduto(LoginRequiredMixin, CreateView):
    model = Produto
    template_name = 'produtos/criar.html'
    form_class = ProdutoForm
    success_url = reverse_lazy('listar_produtos')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['marca_form'] = MarcaForm()
        return ctx


class EditarProduto(LoginRequiredMixin, UpdateView):
    model = Produto
    template_name = 'produtos/editar.html'
    form_class = ProdutoForm
    success_url = reverse_lazy('listar_produtos')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['marca_form'] = MarcaForm()
        return ctx


class ListarProdutoView(LoginRequiredMixin, ListView):
    model = Produto
    template_name = "produtos/listar.html"
    context_object_name = "produtos"
    queryset = Produto.objects.all()


class CadastrarMarca(LoginRequiredMixin, CreateView):
    def post(self, request, *args, **kwargs):
        form = MarcaForm(request.POST)
        if form.is_valid():
            marca = form.save()
            return JsonResponse(
                {'success': True, 'message': 'Marca cadastrada com sucesso!', 'id': marca.id, 'nome': marca.nome})
        else:
            return JsonResponse({'success': False, 'errors': form.errors})

    def get(self, request, *args, **kwargs):
        return JsonResponse({'success': False, 'message': 'Método não permitido.'})


class ExcluirProduto(LoginRequiredMixin, DeleteView):
    model = Produto
    template_name = 'produtos/excluir.html'
    success_url = reverse_lazy('listar_produtos')

templates/produtos/criar.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block conteudo %}
    <div class="d-flex justify-content-center mt-5 mb-5">
        <div class="custom-bg p-4 shadow-lg rounded" style="width: 100%; max-width: 800px;">
            <h2 class="text-center mb-4">Cadastro de Produto</h2>
            <form method="post" novalidate>
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#marcaModal">
                    Cadastrar Marca
                </button>
                <button type="submit" class="btn btn-primary mt-5 w-100">Cadastrar</button>
            </form>
        </div>
        <div class="modal fade" id="marcaModal" tabindex="-1" role="dialog" aria-labelledby="marcaModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="marcaModalLabel">Criar Nova Marca</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form id="marcaForm">
                        {% csrf_token %}
                        <div class="modal-body">
                            {% bootstrap_form marca_form %}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary closeModal" data-dismiss="modal">Fechar
                            </button>
                            <button type="button" class="btn btn-primary" id="saveMarcaButton">Salvar Marca</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        document.getElementById('saveMarcaButton').addEventListener('click', function () {
            const formData = new FormData(document.getElementById('marcaForm'));
            const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;

            fetch("{% url 'cadastrar_marca' %}", {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': csrfToken  // Adiciona o token CSRF no header
                }
            })
                .then(response => response.json())
                .then(data => {
                    let element = document.createElement("option");
                    if (data.success) {
                        document.querySelector('.closeModal').click();
                        document.getElementById('marcaForm').reset();
                        element.value = data['id'];
                        element.textContent = data['nome'];

                        let marca_input = document.querySelector("#id_marca");
                        marca_input.appendChild(element);
                        marca_input.value = data['id'];
                    } else {
                        alert("Não foi possível adicionar marca");
                    }

                })
                .catch(error => {
                    alert("Não foi possível adicionar marca");
                });
        });
    </script>
{% endblock %}

templates/produtos/editar.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block conteudo %}
    <div class="d-flex justify-content-center mt-5 mb-5">
        <div class="custom-bg p-4 shadow-lg rounded" style="width: 100%; max-width: 800px;">
            <h2 class="text-center mb-4">Cadastro de Produto</h2>
            <form method="post" novalidate>
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#marcaModal">
                    Cadastrar Marca
                </button>
                <button type="submit" class="btn btn-primary mt-5 w-100">Salvar</button>
            </form>
        </div>
        <div class="modal fade" id="marcaModal" tabindex="-1" role="dialog" aria-labelledby="marcaModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="marcaModalLabel">Criar Nova Marca</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form id="marcaForm">
                        {% csrf_token %}
                        <div class="modal-body">
                            {% bootstrap_form marca_form %}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary closeModal" data-dismiss="modal">Fechar
                            </button>
                            <button type="button" class="btn btn-primary" id="saveMarcaButton">Salvar Marca</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        document.getElementById('saveMarcaButton').addEventListener('click', function () {
            const formData = new FormData(document.getElementById('marcaForm'));
            const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;

            fetch("{% url 'cadastrar_marca' %}", {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': csrfToken  // Adiciona o token CSRF no header
                }
            })
                .then(response => response.json())
                .then(data => {
                    let element = document.createElement("option");
                    if (data.success) {
                        document.querySelector('.closeModal').click();
                        document.getElementById('marcaForm').reset();
                        element.value = data['id'];
                        element.textContent = data['nome'];

                        let marca_input = document.querySelector("#id_marca");
                        marca_input.appendChild(element);
                        marca_input.value = data['id'];
                    } else {
                        alert("Não foi possível adicionar marca");
                    }

                })
                .catch(error => {
                    alert("Não foi possível adicionar marca");
                });
        });
    </script>
{% endblock %}

templates/produtos/excluir.html
{% extends 'base.html' %}
{% load static %}
{% block conteudo %}
    <div class="container mt-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Excluir Produto</h5>
                <p class="card-text">Tem certeza que deseja excluir o Produto <strong>{{ produto }}</strong>?</p>
                <form method="POST">
                    {% csrf_token %}
                    <div class="d-flex align-items-center mt-4">
                        <!-- Delete button -->
                        <input type="submit" value="Excluir" class="btn btn-danger">
                        &emsp;
                        <!-- Cancel link styled as a button -->
                        <a href="{% url 'listar_produtos' %}" class="btn btn-secondary">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock conteudo %}

templates/produtos/listar.html
{% extends 'base.html' %}
{% load  static %}
{% block conteudo %}
    <div class="container card mt-4 p-5">
        <h2 class="mb-4">Produtos</h2>
        <table class="table table-striped table-hover">
            <thead class="table-dark">
            <tr>
                <th scope="col">Produto</th>
                <th scope="col">Ações</th>
            </tr>
            </thead>
            <tbody>
            {% for produto in produtos %}
                <tr data-bs-toggle="modal" data-bs-target="#produtoModal{{ produto.id }}">
                    <td>{{ produto }}</td>
                    <td>
                        <a href="{% url 'editar_produto' produto.id %}" class="btn btn-outline-secondary btn-sm me-2"
                           role="button">
                            <i class="bi bi-pencil-square"></i>
                        </a>
                        <a href="{% url 'excluir_produto' produto.id %}" class="btn btn-outline-danger btn-sm" role="button">
                            <i class="bi bi-trash"></i>
                        </a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="2" class="text-center">Ainda não existem produtos cadastrados!</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'cadastrar_produto' %}" class="btn btn-primary">Cadastrar Produto</a>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const actionButtons = document.querySelectorAll('.table .btn');
            actionButtons.forEach(function (btn) {
                btn.addEventListener('click', function (event) {
                    event.stopPropagation();  // Prevent modal from opening when action buttons are clicked
                });
            });
        });
    </script>
{% endblock conteudo %}